title: Jonathan Leung
url: "https://jleungs.github.io/"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Posts"
   link: "posts"
 - name: "Projects"
   link: "projects"
